// Default values of the form which will be used to compare if all the input fields have been entered properly (except Checkbox fields as they can be True or False)

export const inputDefaultValues: Object = {
  Pool: false,
  Basement: false,
  'Basement Finish': false,
  Fireplace: false,
  'Attached Garage': false,
  'Detached Garage': false,
  'Air Conditioning': false,
  'Multiple Residences': false,
  Rooms: 0,
  'Year Built': 1850,
  'Total Living Area (sq.ft)': 0,
  'Assessed Land Area (sq.ft)': 0,
  'Total Assessed Value': 0,
  'Sewer Frontage Measurement': 0,
  'Water Frontage Measurement': 0,
  'Neighbourhood Area': '',
  Zoning: '',
  'Sale Month': '',
  'Street Type': '',
  'Building Type': '',
  'Market Region': '',
  'Property Use Code': '',
};

// List that holds the names of all non-checkbox fields used to compare the field values object with the default (except 'Year Built')

export const nonCheckboxFields: string[] = [
  'Rooms',
  'Total Living Area (sq.ft)',
  'Assessed Land Area (sq.ft)',
  'Total Assessed Value',
  'Sewer Frontage Measurement',
  'Water Frontage Measurement',
  'Neighbourhood Area',
  'Zoning',
  'Sale Month',
  'Street Type',
  'Building Type',
  'Market Region',
  'Property Use Code',
];

/*
This below variables hold all of the unique values for the respective feature, sourced from train_model.ipynb notebook
These values will be used as input for Selection dropdown in the the React form 
*/

export const neighbourhoods: string[] = [
  'MELROSE',
  'VICTORIA WEST',
  'KERN PARK',
  'RADISSON',
  'KILDARE-REDONDA',
  'CANTERBURY PARK',
  'MEADOWS',
  'MISSION GARDENS',
  'PEGUIS',
  'GRASSIE',
  'TRANSCONA SOUTH',
  'REGENT',
  'HOLDEN',
  'ST B INDUSTRIAL PARK',
  'MISSION INDUSTRIAL',
  'MAGINOT',
  'MINNETONKA',
  'PULBERRY',
  'VICTORIA CRESCENT',
  'VISTA',
  'WINDSOR PARK',
  'NORMAND PARK',
  'RIVER PARK SOUTH',
  'DAKOTA CROSSING',
  'STOCK YARDS',
  'SOUTHLAND PARK',
  'NIAKWA PARK',
  'NIAKWA PLACE',
  'SOUTHDALE',
  'SAGE CREEK',
  'MEADOWOOD',
  'ROYALWOOD',
  'ISLAND LAKES',
  'FRAIPONT',
  'CHALMERS',
  'TALBOT-GREY',
  'EAST ELMWOOD',
  'MUNROE WEST',
  'GLENELM',
  'KILDONAN DRIVE',
  'MUNROE EAST',
  'ROSSMERE-A',
  'RIVER EAST',
  'SPRINGFIELD NORTH',
  'SPRINGFIELD SOUTH',
  'VALHALLA',
  'VALLEY GARDENS',
  'EAGLEMERE',
  'ROSSMERE-B',
  'LUXTON',
  'JEFFERSON',
  'MYNARSKI',
  'ROBERTSON',
  'ST JOHNS PARK',
  'SEVEN OAKS',
  'GARDEN CITY',
  'THE MAPLES',
  'MARGARET PARK',
  'INKSTER GARDENS',
  'LEILA-MCPHILLIPS TRI',
  'MANDALAY WEST',
  'RIVERGROVE',
  'RIVERBEND',
  'TEMPLETON-SINCLAIR',
  'TYNDALL PARK',
  'N INKSTER INDUSTRIAL',
  'INKSTER INDUSTRIAL',
  'ROSSER-OLD KILDONAN',
  'AMBER TRAILS',
  'CENTENNIAL',
  'WEST BROADWAY',
  'SPENCE',
  'WEST ALEXANDER',
  'DANIEL McINTYRE',
  'ST MATTHEWS',
  'WESTON',
  'MINTO',
  'SARGENT PARK',
  'BROOKLANDS',
  'CENTRAL PARK',
  'DUFFERIN',
  'WILLIAM WHYTE',
  'BURROWS CENTRAL',
  'ST JOHNS',
  'BURROWS-KEEWATIN',
  'INKSTER-FARADAY',
  'NORTH POINT DOUGLAS',
  'SHAUGHNESSY PARK',
  'DUFFERIN INDUSTRIAL',
  'LORD SELKIRK PARK',
  'KENSINGTON',
  'KING EDWARD',
  'BRUCE PARK',
  'DEER LODGE',
  'BIRCHWOOD',
  'BOOTH',
  'BUCHANAN',
  'CRESTVIEW',
  'GLENDALE',
  'HERITAGE PARK',
  'JAMESWOOD',
  'STURGEON CREEK',
  'SILVER HEIGHTS',
  'KIRKFIELD',
  'WOODHAVEN',
  'WESTWOOD',
  'ASSINIBOIA DOWNS',
  'VARSITY VIEW',
  'ERIC COY',
  'MARLTON',
  'RIDGEDALE',
  'RIVER WEST PARK',
  'ROBLIN PARK',
  'SOUTHBOINE',
  'VIALOUX',
  'WESTDALE',
  'BETSWORTH',
  'ELMHURST',
  'RIDGEWOOD SOUTH',
  'BEAUMONT',
  'MAYBANK',
  'POINT ROAD',
  'WILDWOOD',
  'AGASSIZ',
  'CRESCENT PARK',
  'FORT RICHMOND',
  'ST NORBERT',
  'LINDEN WOODS',
  'FAIRFIELD PARK',
  'RICHMOND WEST',
  'MONTCALM',
  'RICHMOND LAKES',
  'WAVERLEY HEIGHTS',
  'WHYTE RIDGE',
  'LINDEN RIDGE',
  'PARC LA SALLE',
  'BRIDGWATER FOREST',
  'SOUTH POINTE',
  'SOUTH POINTE WEST',
  'BRIDGWATER TRAILS',
  'BRIDGWATER LAKES',
  'BRIDGWATER CENTRE',
  'NORTH ST BONIFACE',
  'CENTRAL ST BONIFACE',
  'TISSOT',
  'ARCHWOOD',
  'DUFRESNE',
  'ELM PARK',
  'GLENWOOD',
  'LAVALEE',
  'NORBERRY',
  'NORWOOD EAST',
  'NORWOOD WEST',
  'ST GEORGE',
  'VARENNES',
  'WORTHINGTON',
  'KINGSTON CRESCENT',
  'LEILA NORTH',
  'W K INDUSTRIAL',
  'CIVIC CENTRE',
  'AIRPORT',
  'ST JAMES INDUSTRIAL',
  'EARL GREY',
  'EBBY-WENTWORTH',
  'McMILLAN',
  'RIVER-OSBORNE',
  'WOLSELEY',
  'ROSLYN',
  'WEST WOLSELEY',
  'CRESCENTWOOD',
  'GRANT PARK',
  'ROCKWOOD',
  'CENTRAL RIVER HGTS',
  'J. B. MITCHELL',
  'MATHERS',
  'TUXEDO',
  'NORTH RIVER HEIGHTS',
  'OLD TUXEDO',
  'SIR JOHN FRANKLIN',
  'SOUTH RIVER HEIGHTS',
  'WELLINGTON CRESCENT',
  'SOUTH TUXEDO',
  'LORD ROBERTS',
  'RIVERVIEW',
  'CLOUTIER DRIVE',
];

export const zones: string[] = [
  'R1M - RES - S F - MEDIUM',
  'R2 - RES - TWO FAMILY',
  'C1 - COM - NEIGHBOURHOOD',
  'M1 - MANUFCTRNG - LIGHT',
  'C2 - COM - COMMUNITY',
  'R1L - RES - S F - LARGE',
  'R1S - RES - S F - SMALL',
  'RMFM - RES - MULTI-FAMILY',
  'RMFS - RES - MULTI-FAMILY',
  'A - AGRICULTURAL',
  'R1E - RES - S F - ESTATE',
  'RR5 - RURAL RESIDENTIAL-5',
  'CMU - COMMERCIAL-MIXED USE',
  'M3 - MANUFCTRNG - HEAVY',
  'PR1 - PRKS&REC-PASSIVE',
  'R120 - SINGLE FAMILY',
  'R14 - SINGLE FAMILY',
  'D - DOWNTOWN LIVING',
  'M2 - MANUFCTRNG - GENERAL',
  'R135 - SINGLE FAMILY',
  'PR2 - PRKS&REC-ACTIVE',
  'R15 - SINGLE FAMILY',
  'RMFL - RES - MULTI-FAMILY',
  'M - MULTIPLE-USE',
  '120A - SINGLE FAMILY',
];

export const months: string[] = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const streetType: string[] = [
  'AVENUE',
  'ROAD',
  'STREET',
  'DRIVE',
  'CIRCLE',
  'BAY',
  'CRESCENT',
  'PLACE',
  'COURT',
  'BOULEVARD',
  'WAY',
  'LANE',
  'GROVE',
  'COVE',
  'GATE',
  'GREEN',
  'CLOSE',
  'PROMENADE',
  'POINT',
  'HIGHWAY',
  'WALK',
  'KEY',
  'PATH',
  'ROW',
  'TRAIL',
  'COMMON',
  'SQUARE',
  'PARK',
  'RIDGE',
  'TERRACE',
  'RUN',
];

export const buildingType: string[] = [
  'ONE STOREY',
  'ONE & 1/2 STOREY',
  'ONE & 3/4 STOREY',
  'TWO STOREY',
  'BI-LEVEL',
  '4 LEVEL SPLIT',
  '3 LEVEL SPLIT',
  'TWO/ONE STOREY',
  'CABOVER',
  'TWO & 1/2 STOREY',
];

export const marketRegion: string[] = [
  '1, TRANSCONA',
  '10, NEW ST BONIFACE/NEW ST VITAL',
  '2, EAST KILDONAN / NORTH KILDONAN',
  '3, WEST KILDONAN / OLD KILDONAN',
  '4, INNER CITY',
  '5, ST. JAMES',
  '6, CHARLESWOOD',
  '8, FORT GARRY / LINDENWOODS',
  '9, OLD ST BONIFACE/OLD ST VITAL',
  '7, TUXEDO / RIVER HEIGHTS / FT ROUGE',
];

export const propertyUseCode: string[] = [
  'RESSD - DETACHED SINGLE DWELLING',
  'RESMC - MULTIFAMILY CONVERSION',
  'RESSU - RESIDENTIAL SECONDARY UNIT',
  'RESSS - SIDE BY SIDE',
  'RESRH - ROW HOUSING',
  'RESDU - DUPLEX',
  'RESTR - TRIPLEX',
  'RESMA - MULTIPLE ATTACHED UNITS',
];
